# docker-compose.yml - Configuración para Podman
version: '3.8'

services:
  # ==========================================
  # APLICACIÓN PRINCIPAL
  # ==========================================
  app:
    build: .
    container_name: evento-speaker-assistant
    ports:
      - "7860:7860"  # Aplicación Gradio
      - "8000:8000"  # Métricas Prometheus
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./assets:/app/assets
      - ./data:/app/data:ro
      - ./logs:/app/logs
      - ./cache:/app/.cache  # Cache para HuggingFace
    # Opción 1: Usar host network para acceso completo
    networks:
      - network_llm
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ==========================================
  # REDIS (opcional, para cache de aplicación)
  # ==========================================
  redis:
    image: redis:7-alpine
    container_name: evento-speaker-redis
    restart: unless-stopped
    networks:
      - network_llm
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - cache  # Solo se ejecuta si especificas --profile cache

# ==========================================
# VOLÚMENES PERSISTENTES
# ==========================================
volumes:
  redis_data:
    driver: local

networks:
  network_llm:
    external: true
    name: llm