# docker-compose.yml - Solo la aplicación, sin servicios de BD
version: '3.8'

services:
  app:
    build: .
    container_name: evento-speaker-assistant
    ports:
      - "7860:7860"  # Aplicación Gradio
      - "8000:8000"  # Métricas Prometheus
    environment:
      - APP_TITLE=Evento Speaker Assistant 🎤
      - CONFIG_FILE=config.yaml
      - DB_TYPE=FAISS  # O cambia por REDIS/PGVECTOR/ELASTIC si usas BD externa
      - TIMEOUT=60
      - PROMETHEUS_PORT=8000
      - DEBUG=true
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./assets:/app/assets
      - ./data:/app/data
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - evento-network

# Red para la aplicación
networks:
  evento-network:
    driver: bridge